namespace App_Chat.View
{
    partial class ForgotPassword
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ForgotPassword));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btn_change_pwd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tb_OTP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_re_new_pwd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_new_pwd = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lb_warning = new System.Windows.Forms.Label();
            this.tb_username = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_send_OTP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tb_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.btn_change_pwd);
            this.panel1.Controls.Add(this.tb_OTP);
            this.panel1.Controls.Add(this.tb_re_new_pwd);
            this.panel1.Controls.Add(this.tb_new_pwd);
            this.panel1.Controls.Add(this.lb_warning);
            this.panel1.Controls.Add(this.tb_username);
            this.panel1.Controls.Add(this.btn_send_OTP);
            this.panel1.Controls.Add(this.tb_email);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(555, 427);
            this.panel1.TabIndex = 0;
            // 
            // btn_change_pwd
            // 
            this.btn_change_pwd.AllowAnimations = true;
            this.btn_change_pwd.AllowMouseEffects = true;
            this.btn_change_pwd.AllowToggling = false;
            this.btn_change_pwd.AnimationSpeed = 200;
            this.btn_change_pwd.AutoGenerateColors = false;
            this.btn_change_pwd.AutoRoundBorders = false;
            this.btn_change_pwd.AutoSizeLeftIcon = true;
            this.btn_change_pwd.AutoSizeRightIcon = true;
            this.btn_change_pwd.BackColor = System.Drawing.Color.Transparent;
            this.btn_change_pwd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_change_pwd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_change_pwd.BackgroundImage")));
            this.btn_change_pwd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_change_pwd.ButtonText = "Đổi mật khẩu";
            this.btn_change_pwd.ButtonTextMarginLeft = 0;
            this.btn_change_pwd.ColorContrastOnClick = 45;
            this.btn_change_pwd.ColorContrastOnHover = 45;
            this.btn_change_pwd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_change_pwd.CustomizableEdges = borderEdges1;
            this.btn_change_pwd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_change_pwd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_change_pwd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_change_pwd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_change_pwd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_change_pwd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_change_pwd.ForeColor = System.Drawing.Color.White;
            this.btn_change_pwd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_change_pwd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_change_pwd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_change_pwd.IconMarginLeft = 11;
            this.btn_change_pwd.IconPadding = 10;
            this.btn_change_pwd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_change_pwd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_change_pwd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_change_pwd.IconSize = 25;
            this.btn_change_pwd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_change_pwd.IdleBorderRadius = 35;
            this.btn_change_pwd.IdleBorderThickness = 1;
            this.btn_change_pwd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_change_pwd.IdleIconLeftImage = null;
            this.btn_change_pwd.IdleIconRightImage = null;
            this.btn_change_pwd.IndicateFocus = false;
            this.btn_change_pwd.Location = new System.Drawing.Point(213, 340);
            this.btn_change_pwd.Name = "btn_change_pwd";
            this.btn_change_pwd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_change_pwd.OnDisabledState.BorderRadius = 35;
            this.btn_change_pwd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_change_pwd.OnDisabledState.BorderThickness = 1;
            this.btn_change_pwd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_change_pwd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_change_pwd.OnDisabledState.IconLeftImage = null;
            this.btn_change_pwd.OnDisabledState.IconRightImage = null;
            this.btn_change_pwd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_change_pwd.onHoverState.BorderRadius = 35;
            this.btn_change_pwd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_change_pwd.onHoverState.BorderThickness = 1;
            this.btn_change_pwd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_change_pwd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_change_pwd.onHoverState.IconLeftImage = null;
            this.btn_change_pwd.onHoverState.IconRightImage = null;
            this.btn_change_pwd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_change_pwd.OnIdleState.BorderRadius = 35;
            this.btn_change_pwd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_change_pwd.OnIdleState.BorderThickness = 1;
            this.btn_change_pwd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_change_pwd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_change_pwd.OnIdleState.IconLeftImage = null;
            this.btn_change_pwd.OnIdleState.IconRightImage = null;
            this.btn_change_pwd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_change_pwd.OnPressedState.BorderRadius = 35;
            this.btn_change_pwd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_change_pwd.OnPressedState.BorderThickness = 1;
            this.btn_change_pwd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_change_pwd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_change_pwd.OnPressedState.IconLeftImage = null;
            this.btn_change_pwd.OnPressedState.IconRightImage = null;
            this.btn_change_pwd.Size = new System.Drawing.Size(114, 44);
            this.btn_change_pwd.TabIndex = 23;
            this.btn_change_pwd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_change_pwd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_change_pwd.TextMarginLeft = 0;
            this.btn_change_pwd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_change_pwd.UseDefaultRadiusAndThickness = true;
            this.btn_change_pwd.Visible = false;
            this.btn_change_pwd.Click += new System.EventHandler(this.btn_change_pwd_Click);
            // 
            // tb_OTP
            // 
            this.tb_OTP.AcceptsReturn = false;
            this.tb_OTP.AcceptsTab = false;
            this.tb_OTP.AnimationSpeed = 200;
            this.tb_OTP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_OTP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_OTP.BackColor = System.Drawing.Color.Transparent;
            this.tb_OTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_OTP.BackgroundImage")));
            this.tb_OTP.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_OTP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_OTP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_OTP.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_OTP.BorderRadius = 10;
            this.tb_OTP.BorderThickness = 1;
            this.tb_OTP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_OTP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_OTP.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_OTP.DefaultText = "";
            this.tb_OTP.FillColor = System.Drawing.Color.White;
            this.tb_OTP.HideSelection = true;
            this.tb_OTP.IconLeft = null;
            this.tb_OTP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_OTP.IconPadding = 10;
            this.tb_OTP.IconRight = null;
            this.tb_OTP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_OTP.Lines = new string[0];
            this.tb_OTP.Location = new System.Drawing.Point(115, 285);
            this.tb_OTP.MaxLength = 32767;
            this.tb_OTP.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_OTP.Modified = false;
            this.tb_OTP.Multiline = false;
            this.tb_OTP.Name = "tb_OTP";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_OTP.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_OTP.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_OTP.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_OTP.OnIdleState = stateProperties4;
            this.tb_OTP.Padding = new System.Windows.Forms.Padding(3);
            this.tb_OTP.PasswordChar = '\0';
            this.tb_OTP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_OTP.PlaceholderText = "Nhập mã OTP";
            this.tb_OTP.ReadOnly = false;
            this.tb_OTP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_OTP.SelectedText = "";
            this.tb_OTP.SelectionLength = 0;
            this.tb_OTP.SelectionStart = 0;
            this.tb_OTP.ShortcutsEnabled = true;
            this.tb_OTP.Size = new System.Drawing.Size(311, 37);
            this.tb_OTP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_OTP.TabIndex = 27;
            this.tb_OTP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_OTP.TextMarginBottom = 0;
            this.tb_OTP.TextMarginLeft = 3;
            this.tb_OTP.TextMarginTop = 0;
            this.tb_OTP.TextPlaceholder = "Nhập mã OTP";
            this.tb_OTP.UseSystemPasswordChar = false;
            this.tb_OTP.Visible = false;
            this.tb_OTP.WordWrap = true;
            // 
            // tb_re_new_pwd
            // 
            this.tb_re_new_pwd.AcceptsReturn = false;
            this.tb_re_new_pwd.AcceptsTab = false;
            this.tb_re_new_pwd.AnimationSpeed = 200;
            this.tb_re_new_pwd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_re_new_pwd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_re_new_pwd.BackColor = System.Drawing.Color.Transparent;
            this.tb_re_new_pwd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_re_new_pwd.BackgroundImage")));
            this.tb_re_new_pwd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_re_new_pwd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_re_new_pwd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_re_new_pwd.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_re_new_pwd.BorderRadius = 10;
            this.tb_re_new_pwd.BorderThickness = 1;
            this.tb_re_new_pwd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_re_new_pwd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_re_new_pwd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_re_new_pwd.DefaultText = "";
            this.tb_re_new_pwd.FillColor = System.Drawing.Color.White;
            this.tb_re_new_pwd.HideSelection = true;
            this.tb_re_new_pwd.IconLeft = null;
            this.tb_re_new_pwd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_re_new_pwd.IconPadding = 10;
            this.tb_re_new_pwd.IconRight = null;
            this.tb_re_new_pwd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_re_new_pwd.Lines = new string[0];
            this.tb_re_new_pwd.Location = new System.Drawing.Point(115, 233);
            this.tb_re_new_pwd.MaxLength = 32767;
            this.tb_re_new_pwd.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_re_new_pwd.Modified = false;
            this.tb_re_new_pwd.Multiline = false;
            this.tb_re_new_pwd.Name = "tb_re_new_pwd";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_re_new_pwd.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_re_new_pwd.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_re_new_pwd.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_re_new_pwd.OnIdleState = stateProperties8;
            this.tb_re_new_pwd.Padding = new System.Windows.Forms.Padding(3);
            this.tb_re_new_pwd.PasswordChar = '\0';
            this.tb_re_new_pwd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_re_new_pwd.PlaceholderText = "Nhập lại mật khẩu mới";
            this.tb_re_new_pwd.ReadOnly = false;
            this.tb_re_new_pwd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_re_new_pwd.SelectedText = "";
            this.tb_re_new_pwd.SelectionLength = 0;
            this.tb_re_new_pwd.SelectionStart = 0;
            this.tb_re_new_pwd.ShortcutsEnabled = true;
            this.tb_re_new_pwd.Size = new System.Drawing.Size(311, 37);
            this.tb_re_new_pwd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_re_new_pwd.TabIndex = 26;
            this.tb_re_new_pwd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_re_new_pwd.TextMarginBottom = 0;
            this.tb_re_new_pwd.TextMarginLeft = 3;
            this.tb_re_new_pwd.TextMarginTop = 0;
            this.tb_re_new_pwd.TextPlaceholder = "Nhập lại mật khẩu mới";
            this.tb_re_new_pwd.UseSystemPasswordChar = false;
            this.tb_re_new_pwd.Visible = false;
            this.tb_re_new_pwd.WordWrap = true;
            // 
            // tb_new_pwd
            // 
            this.tb_new_pwd.AcceptsReturn = false;
            this.tb_new_pwd.AcceptsTab = false;
            this.tb_new_pwd.AnimationSpeed = 200;
            this.tb_new_pwd.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_new_pwd.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_new_pwd.BackColor = System.Drawing.Color.Transparent;
            this.tb_new_pwd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_new_pwd.BackgroundImage")));
            this.tb_new_pwd.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_new_pwd.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_new_pwd.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_new_pwd.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_new_pwd.BorderRadius = 10;
            this.tb_new_pwd.BorderThickness = 1;
            this.tb_new_pwd.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_new_pwd.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_new_pwd.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_new_pwd.DefaultText = "";
            this.tb_new_pwd.FillColor = System.Drawing.Color.White;
            this.tb_new_pwd.HideSelection = true;
            this.tb_new_pwd.IconLeft = null;
            this.tb_new_pwd.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_new_pwd.IconPadding = 10;
            this.tb_new_pwd.IconRight = null;
            this.tb_new_pwd.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_new_pwd.Lines = new string[0];
            this.tb_new_pwd.Location = new System.Drawing.Point(115, 181);
            this.tb_new_pwd.MaxLength = 32767;
            this.tb_new_pwd.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_new_pwd.Modified = false;
            this.tb_new_pwd.Multiline = false;
            this.tb_new_pwd.Name = "tb_new_pwd";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_new_pwd.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_new_pwd.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_new_pwd.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_new_pwd.OnIdleState = stateProperties12;
            this.tb_new_pwd.Padding = new System.Windows.Forms.Padding(3);
            this.tb_new_pwd.PasswordChar = '\0';
            this.tb_new_pwd.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_new_pwd.PlaceholderText = "Nhập mật khẩu mới";
            this.tb_new_pwd.ReadOnly = false;
            this.tb_new_pwd.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_new_pwd.SelectedText = "";
            this.tb_new_pwd.SelectionLength = 0;
            this.tb_new_pwd.SelectionStart = 0;
            this.tb_new_pwd.ShortcutsEnabled = true;
            this.tb_new_pwd.Size = new System.Drawing.Size(311, 37);
            this.tb_new_pwd.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_new_pwd.TabIndex = 25;
            this.tb_new_pwd.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_new_pwd.TextMarginBottom = 0;
            this.tb_new_pwd.TextMarginLeft = 3;
            this.tb_new_pwd.TextMarginTop = 0;
            this.tb_new_pwd.TextPlaceholder = "Nhập mật khẩu mới";
            this.tb_new_pwd.UseSystemPasswordChar = false;
            this.tb_new_pwd.Visible = false;
            this.tb_new_pwd.WordWrap = true;
            this.tb_new_pwd.TextChanged += new System.EventHandler(this.tb_new_pwd_TextChanged);
            // 
            // lb_warning
            // 
            this.lb_warning.AutoSize = true;
            this.lb_warning.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lb_warning.ForeColor = System.Drawing.Color.Red;
            this.lb_warning.Location = new System.Drawing.Point(115, 325);
            this.lb_warning.Name = "lb_warning";
            this.lb_warning.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lb_warning.Size = new System.Drawing.Size(0, 17);
            this.lb_warning.TabIndex = 24;
            this.lb_warning.Visible = false;
            // 
            // tb_username
            // 
            this.tb_username.AcceptsReturn = false;
            this.tb_username.AcceptsTab = false;
            this.tb_username.AnimationSpeed = 200;
            this.tb_username.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_username.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_username.BackColor = System.Drawing.Color.Transparent;
            this.tb_username.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_username.BackgroundImage")));
            this.tb_username.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_username.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_username.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_username.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_username.BorderRadius = 10;
            this.tb_username.BorderThickness = 1;
            this.tb_username.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_username.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_username.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_username.DefaultText = "";
            this.tb_username.FillColor = System.Drawing.Color.White;
            this.tb_username.HideSelection = true;
            this.tb_username.IconLeft = null;
            this.tb_username.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_username.IconPadding = 10;
            this.tb_username.IconRight = null;
            this.tb_username.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_username.Lines = new string[0];
            this.tb_username.Location = new System.Drawing.Point(77, 41);
            this.tb_username.MaxLength = 32767;
            this.tb_username.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_username.Modified = false;
            this.tb_username.Multiline = false;
            this.tb_username.Name = "tb_username";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_username.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_username.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_username.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_username.OnIdleState = stateProperties16;
            this.tb_username.Padding = new System.Windows.Forms.Padding(3);
            this.tb_username.PasswordChar = '\0';
            this.tb_username.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_username.PlaceholderText = "Nhập username";
            this.tb_username.ReadOnly = false;
            this.tb_username.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_username.SelectedText = "";
            this.tb_username.SelectionLength = 0;
            this.tb_username.SelectionStart = 0;
            this.tb_username.ShortcutsEnabled = true;
            this.tb_username.Size = new System.Drawing.Size(280, 37);
            this.tb_username.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_username.TabIndex = 3;
            this.tb_username.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_username.TextMarginBottom = 0;
            this.tb_username.TextMarginLeft = 3;
            this.tb_username.TextMarginTop = 0;
            this.tb_username.TextPlaceholder = "Nhập username";
            this.tb_username.UseSystemPasswordChar = false;
            this.tb_username.WordWrap = true;
            // 
            // btn_send_OTP
            // 
            this.btn_send_OTP.AllowAnimations = true;
            this.btn_send_OTP.AllowMouseEffects = true;
            this.btn_send_OTP.AllowToggling = false;
            this.btn_send_OTP.AnimationSpeed = 200;
            this.btn_send_OTP.AutoGenerateColors = false;
            this.btn_send_OTP.AutoRoundBorders = false;
            this.btn_send_OTP.AutoSizeLeftIcon = true;
            this.btn_send_OTP.AutoSizeRightIcon = true;
            this.btn_send_OTP.BackColor = System.Drawing.Color.Transparent;
            this.btn_send_OTP.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_send_OTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_send_OTP.BackgroundImage")));
            this.btn_send_OTP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_send_OTP.ButtonText = "Gửi OTP";
            this.btn_send_OTP.ButtonTextMarginLeft = 0;
            this.btn_send_OTP.ColorContrastOnClick = 45;
            this.btn_send_OTP.ColorContrastOnHover = 45;
            this.btn_send_OTP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_send_OTP.CustomizableEdges = borderEdges2;
            this.btn_send_OTP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_send_OTP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_send_OTP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_send_OTP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_send_OTP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_send_OTP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_send_OTP.ForeColor = System.Drawing.Color.White;
            this.btn_send_OTP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_send_OTP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_send_OTP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_send_OTP.IconMarginLeft = 11;
            this.btn_send_OTP.IconPadding = 10;
            this.btn_send_OTP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_send_OTP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_send_OTP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_send_OTP.IconSize = 25;
            this.btn_send_OTP.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_send_OTP.IdleBorderRadius = 35;
            this.btn_send_OTP.IdleBorderThickness = 1;
            this.btn_send_OTP.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_send_OTP.IdleIconLeftImage = null;
            this.btn_send_OTP.IdleIconRightImage = null;
            this.btn_send_OTP.IndicateFocus = false;
            this.btn_send_OTP.Location = new System.Drawing.Point(399, 61);
            this.btn_send_OTP.Name = "btn_send_OTP";
            this.btn_send_OTP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_send_OTP.OnDisabledState.BorderRadius = 35;
            this.btn_send_OTP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_send_OTP.OnDisabledState.BorderThickness = 1;
            this.btn_send_OTP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_send_OTP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_send_OTP.OnDisabledState.IconLeftImage = null;
            this.btn_send_OTP.OnDisabledState.IconRightImage = null;
            this.btn_send_OTP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_send_OTP.onHoverState.BorderRadius = 35;
            this.btn_send_OTP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_send_OTP.onHoverState.BorderThickness = 1;
            this.btn_send_OTP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_send_OTP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_send_OTP.onHoverState.IconLeftImage = null;
            this.btn_send_OTP.onHoverState.IconRightImage = null;
            this.btn_send_OTP.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_send_OTP.OnIdleState.BorderRadius = 35;
            this.btn_send_OTP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_send_OTP.OnIdleState.BorderThickness = 1;
            this.btn_send_OTP.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_send_OTP.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_send_OTP.OnIdleState.IconLeftImage = null;
            this.btn_send_OTP.OnIdleState.IconRightImage = null;
            this.btn_send_OTP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_send_OTP.OnPressedState.BorderRadius = 35;
            this.btn_send_OTP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_send_OTP.OnPressedState.BorderThickness = 1;
            this.btn_send_OTP.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_send_OTP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_send_OTP.OnPressedState.IconLeftImage = null;
            this.btn_send_OTP.OnPressedState.IconRightImage = null;
            this.btn_send_OTP.Size = new System.Drawing.Size(109, 44);
            this.btn_send_OTP.TabIndex = 2;
            this.btn_send_OTP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_send_OTP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_send_OTP.TextMarginLeft = 0;
            this.btn_send_OTP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_send_OTP.UseDefaultRadiusAndThickness = true;
            this.btn_send_OTP.Click += new System.EventHandler(this.btn_send_OTP_Click);
            // 
            // tb_email
            // 
            this.tb_email.AcceptsReturn = false;
            this.tb_email.AcceptsTab = false;
            this.tb_email.AnimationSpeed = 200;
            this.tb_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_email.BackColor = System.Drawing.Color.Transparent;
            this.tb_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_email.BackgroundImage")));
            this.tb_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_email.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_email.BorderRadius = 10;
            this.tb_email.BorderThickness = 1;
            this.tb_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_email.DefaultText = "";
            this.tb_email.FillColor = System.Drawing.Color.White;
            this.tb_email.HideSelection = true;
            this.tb_email.IconLeft = null;
            this.tb_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.IconPadding = 10;
            this.tb_email.IconRight = null;
            this.tb_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.Lines = new string[0];
            this.tb_email.Location = new System.Drawing.Point(77, 96);
            this.tb_email.MaxLength = 32767;
            this.tb_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_email.Modified = false;
            this.tb_email.Multiline = false;
            this.tb_email.Name = "tb_email";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_email.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnIdleState = stateProperties20;
            this.tb_email.Padding = new System.Windows.Forms.Padding(3);
            this.tb_email.PasswordChar = '\0';
            this.tb_email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_email.PlaceholderText = "Nhập email";
            this.tb_email.ReadOnly = false;
            this.tb_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_email.SelectedText = "";
            this.tb_email.SelectionLength = 0;
            this.tb_email.SelectionStart = 0;
            this.tb_email.ShortcutsEnabled = true;
            this.tb_email.Size = new System.Drawing.Size(280, 37);
            this.tb_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_email.TabIndex = 0;
            this.tb_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_email.TextMarginBottom = 0;
            this.tb_email.TextMarginLeft = 3;
            this.tb_email.TextMarginTop = 0;
            this.tb_email.TextPlaceholder = "Nhập email";
            this.tb_email.UseSystemPasswordChar = false;
            this.tb_email.WordWrap = true;
            // 
            // ForgotPassword
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(555, 427);
            this.Controls.Add(this.panel1);
            this.Name = "ForgotPassword";
            this.Text = "ForgotPassword";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextBox tb_email;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_send_OTP;
        private Bunifu.UI.WinForms.BunifuTextBox tb_username;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_change_pwd;
        private Bunifu.UI.WinForms.BunifuTextBox tb_OTP;
        private Bunifu.UI.WinForms.BunifuTextBox tb_re_new_pwd;
        private Bunifu.UI.WinForms.BunifuTextBox tb_new_pwd;
        private System.Windows.Forms.Label lb_warning;
    }
}